### ISSUE TITLE
Make command fails with 'patsopt' not found

### ISSUE THREAD

**Issue by ealione** [galletti94/ATS-blockchain#2]
Following the directions provided on the README file and after installing ATS I get

```
$ make regress
\
make -C lambda -f Makefile compile
make[1]: Entering directory '/home/var/ATS-blockchain-master/lambda'
\
make -C example -f Makefile fibo
make[2]: Entering directory '/home/var/ATS-blockchain-master/lambda/example'
/home/var/ATS/lib/ats2-postiats-0.3.9/bin/patscc -D_GNU_SOURCE -DATS_MEMALLOC_LIBC -o fibo_dats fibo.dats
sh: 1: patsopt: not found
Makefile:43: recipe for target 'fibo_dats' failed
make[2]: *** [fibo_dats] Error 1
make[2]: Leaving directory '/home/var/ATS-blockchain-master/lambda/example'
Makefile:16: recipe for target 'fibo' failed
make[1]: *** [fibo] Error 2
make[1]: Leaving directory '/home/var/ATS-blockchain-master/lambda'
Makefile:17: recipe for target 'lambda' failed
make: *** [lambda] Error 2
```
PATSHOME is set with 

`export PATSHOME=/home/var/ATS/lib/ats2-postiats-0.3.9`

**Comment by gallettilance** [comment]
Thanks for the bug report!

This is probably an issue with your ATS installation - to confirm ATS is installed correctly, can your run "patsopt" in the terminal? The output should be "Hello from ATS2(ATS/Postiats)!".

If you do not see this message, please navigate to PATSHOME and run the install-sh shell script. Please post any additional errors should they occur :)

**Comment by gallettilance** [comment]
Btw, are you on linux?

**Comment by ealione** [comment]
Hi!
yes I am using linux mint 18.04. I only installed ATS to follow your tutorial and had no prior knowledge of ATS, you were correct though it was an issue with my installation of ATS2. Thanks for the help :)

**Comment by gallettilance** [comment]
Great! I will close this issue for now but feel free to create a new one should you have questions or run into other bugs!

Happy coding in ATS :)
